---
-
  hosts: test
  name: "This sets up an httpd webserverssss"
  tasks:
    -
      name: "Install apache packageSSSS"
      yum:
        name: httpd
        state: absent
    -
      name: "ensure httpd is running"
      service:
        name: httpd
        state: stopped