#####################################################
#This Playbook is used for patching the linux VMs   #
# Usage:                                            #
# ansible-playbook --user=test -kK                  #
#note: CheckKernelReboot.sh should be in same       #
#       directory where LinuxPatching.yaml exists   #
#####################################################
---
## Sending the Patching starting communication
- hosts: localhost
  #user: test
  #become: yes
  #become_method: sudo
  #become_user: root
  tasks:
   - name: Sending the Notification
     mail:
      host: smtp.gmail.com
      port: 587
      username: nakul.panwar77@gmail.com
      password: newpassword@123
      to: nakul.panwar@accenture.com
      #cc: sumesh.purushothaman@accenture.com
      subject: "Patching: Statrted"
      body: This is test mail to check the script functioanitly,Please ignore..
     delegate_to: localhost
###Patching and rebooting the servers
- hosts: test
  tasks:
   - name: updating the Http pacagge
     yum:
       name: 'httpd'
       state: latest
   - name: Comparing last kernel and running kernel
     script: /root/CheckKernelReboot.sh
     args:
      creates: /root/CheckKernelReboot.sh
   - name: Checking if reboot flag exists
     stat:
       path: /tmp/reboot
     register: reboot
   - name: Clearing reboot flag
     file:
       path: /tmp/reboot
       state: absent
     when: reboot.stat.exists == true
   - name: Rebooting host(s).
     shell: sleep 2 && /sbin/shutdown -r now "Reboot required for updated kernel." && sleep 2
     async: 20
     poll: 0
     when: reboot.stat.exists == true
   - name: Waiting for host(s) to reboot
     wait_for_connection:
       delay: 60
       timeout: 300
     when: reboot.stat.exists == true
### Sending the completed communication
- hosts: localhost
  tasks:
   - name: Sending the Notification
     mail:
      host: smtp.gmail.com
      port: 587
      username: nakul.panwar77@gmail.com
      password: newpassword@123
      to: nakul.panwar@accenture.com
      #cc: sumesh.purushothaman@accenture.com
      subject: "Patching: Completed"
      body: This is test mail to check the script functioanitly,Please ignore..
     delegate_to: localhost
