---
- name: Performing yum update on host(s)
  hosts: test
  #become: yes
  any_errors_fatal: false
#- name: Sending an e-mail using Gmail SMTP servers
  mail:
    host: smtp.gmail.com
    port: 587
    username: nakul.panwar77@gmail.com
    password: newpassword@123
    to: nakul.panwar@accenture.com
    subject: Ansible-report
    body: System {{ ansible_hostname }} has been successfully provisioned.
  delegate_to: localhost
- name: Updating all packages
  yum:
    name: 'httpd'
    state: latest

